services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: number_server
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net

networks:
  app-net:
    driver: bridge